"""SkyVanta AI Deployment & Service Boundary Layer.

Provides configuration adapters, health check services, structured logging,
release verification, startup validation, graceful shutdown, failure recovery,
and data contracts for containerized, API-driven, and WebSocket deployment.
"""

from skyvanta.deployment.config import DeploymentConfig, DeploymentEnvironment
from skyvanta.deployment.contracts import (
    DeploymentHealthContract,
    DeploymentReadinessContract,
    HealthStatus,
    MetricsResponseContract,
    ScenarioRunRequest,
    ScenarioRunResponse,
    SimulationStatus,
    TelemetryStreamPacket,
)
from skyvanta.deployment.health import HealthCheckService
from skyvanta.deployment.logging import DeploymentLogger, JSONDeploymentFormatter
from skyvanta.deployment.observability import (
    DeploymentReadinessContract as ObservabilityReadinessContract,
    EventLogger,
    EventType,
    LatencyStats,
    MetricsCollector,
    ObservabilityMiddleware,
    RateLimitingMiddleware,
    ReadinessService,
    RouteNormalizer,
    StructuredEvent,
    SystemResourceMonitor,
    event_logger,
    metrics_collector,
    readiness_service,
    redact_sensitive_data,
    system_resource_monitor,
)

from skyvanta.deployment.release import (
    ReleaseManifest,
    ReleaseVerificationResult,
    ReleaseVerifier,
    detect_git_metadata,
)
from skyvanta.deployment.reliability import (
    FailureCategory,
    RecoveryAction,
    RecoveryDecision,
    RecoveryManager,
    ShutdownCoordinator,
    ShutdownResult,
    StartupValidationError,
    StartupValidationResult,
    StartupValidator,
    recovery_manager,
    shutdown_coordinator,
)

from skyvanta.deployment.security import (
    APIKeyManager,
    APIKeyRecord,
    PayloadLimitMiddleware,
    RateLimitTier,
    Scope,
    SecurityAuditEvent,
    SecurityAuditLogger,
    SecurityEventType,
    TieredTokenBucketRateLimiter,
    api_key_manager,
    authenticate_websocket,
    extract_api_key_from_request,
    get_current_api_key,
    has_scope,
    hash_key_secret,
    mask_api_key,
    rate_limiter,
    require_scope,
    sanitize_headers,
    sanitize_payload,
    security_audit_logger,
)

__all__ = [
    "DeploymentConfig",
    "DeploymentEnvironment",
    "DeploymentHealthContract",
    "DeploymentReadinessContract",
    "MetricsResponseContract",
    "HealthStatus",
    "SimulationStatus",
    "ScenarioRunRequest",
    "ScenarioRunResponse",
    "TelemetryStreamPacket",
    "HealthCheckService",
    "DeploymentLogger",
    "JSONDeploymentFormatter",
    "EventType",
    "StructuredEvent",
    "EventLogger",
    "event_logger",
    "redact_sensitive_data",
    "MetricsCollector",
    "metrics_collector",
    "LatencyStats",
    "RouteNormalizer",
    "SystemResourceMonitor",
    "system_resource_monitor",
    "ReadinessService",
    "readiness_service",
    "ObservabilityMiddleware",
    "RateLimitingMiddleware",
    "Scope",
    "has_scope",
    "APIKeyRecord",
    "APIKeyManager",
    "api_key_manager",
    "hash_key_secret",
    "get_current_api_key",
    "require_scope",
    "extract_api_key_from_request",
    "authenticate_websocket",
    "RateLimitTier",
    "TieredTokenBucketRateLimiter",
    "rate_limiter",
    "SecurityEventType",
    "SecurityAuditEvent",
    "SecurityAuditLogger",
    "security_audit_logger",
    "mask_api_key",
    "sanitize_headers",
    "sanitize_payload",
    "PayloadLimitMiddleware",
    "ReleaseManifest",
    "ReleaseVerifier",
    "ReleaseVerificationResult",
    "detect_git_metadata",
    "StartupValidator",
    "StartupValidationError",
    "StartupValidationResult",
    "ShutdownCoordinator",
    "ShutdownResult",
    "shutdown_coordinator",
    "FailureCategory",
    "RecoveryAction",
    "RecoveryDecision",
    "RecoveryManager",
    "recovery_manager",
]
